name: Deploy Front (event-manager)

on:
  push:
    branches: [ "main" ]
    paths:
      - "event-manager/**"
      - ".github/workflows/deploy-front.yml"

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (front)
        uses: docker/build-push-action@v6
        with:
          context: ./event-manager
          push: true
          tags: |
            btwpkh/event-manager:latest
            btwpkh/event-manager:${{ github.sha }}

      - name: Deploy to Server (tenant-1)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /service/event-manager/tenants/tenant-1
            docker compose pull
            docker compose up -d
            docker image prune -f
